name: Build and Copy Resume to Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build Check:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      volumes:
        - ${{ github.workspace }}:/usr/src/app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print current directory structure
        run: ls -la
      - name: Build
        run: lualatex resume.tex -o resume.pdf
  Upload To Website:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes resume to website
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "resume.pdf"
          destination_repo: "jaasonw/jason-wong.me"
          destination_folder: "files"
          destination_branch: "master"
          user_email: "noreply@github.com"
          user_name: "github-action"
          commit_message: "Update resume.pdf"
